apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rust
  namespace: argo-rust
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: public
  rules:
    - host: rust.voloshko.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-rust
                port:
                  number: 80
