apiVersion: v1
kind: Service
metadata:
  name: argo-rust
  namespace: argo-rust
spec:
  type: NodePort
  selector:
    app: argo-rust
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30800
